apiVersion: api.hubert.test/v1alpha1
kind: Scaler
metadata:
  name: scaler-sample
spec:
  # TODO(user): Add fields here
  start: 7
  end: 23
  replicas: 4
  deployments:
    - name: nginx
      namespace: default
